global:
  scrape_interval: 15s
  scrape_timeout: 10s

rule_files:
  - alert.yml

scrape_configs:
  - job_name: spring-boot
    metrics_path: /actuator/prometheus
    scrape_interval: 15s
    static_configs:
      - targets:
        - 'metrics-tutorial:8080'
#        - 'host.docker.internal:8080'
  - job_name: prometheus
    metrics_path: /metrics
    static_configs:
      - targets:
          - 'prometheus:9090'
